{% set version = "5.0" %}
{% set sha256 = "60cbc4bad079753721d32649545505362c754e121570ada4658b852a3a318d95" %}

package:
  name: boolean.py
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/b/boolean.py/boolean_py-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - boolean

about:
  home: https://github.com/bastikr/boolean.py
  license: BSD-2-Clause
  license_file: LICENSE.txt
  summary: >
    Define boolean algebras, create and parse boolean expressions and create custom boolean DSL.
  doc_url: https://booleanpy.readthedocs.io/
  dev_url: https://github.com/bastikr/boolean.py

extra:
  recipe-maintainers:
    - mbargull
    - pkgw
