travis:
  secure:
    BINSTAR_TOKEN: wO8fInm1Ydjj+/9t7JHxzTMZ6uHzj3gaK7Lf0v0/QYQqB33q/e090yyz7pQghKp1Pu28y4ePqGjPC+F549Uwv7njotsPJLGjd596KSiVgJYZn9wFzqafRvMG1ojPt/qZWB+qNEpUS7+cm4WUjkVPZ6K06nQR+wgsxpyitJzmhTlNEWDfUSvfrLe2eOM8auppeynEngKAQo0yIxflDenctgya71UrgGCTYhweciolptrq++yEJfN9197jTxYGFWvqjGuXSu2wxLbF0QQnY20oUbrXM0im7xth0P4ck+7ZbQA6QuAMki5TZ4J5Z99a7TlD+Q59qf6ugLddK9cnTrurPTZHDZNtbRq04UcOGlh98YOY0ccvvMoNzljZaqMcdJDECdFpqN6ZF3ZP6Qagyz33DHTV+4ydJ0kDOEgHGB5U41pLd8cxPHnX+WS/RVqQ6qg/v3KCaz2Y3K4X4Hh3qHCwfkuDEJWe8enRvse2IlENRjL+7BPAMfAtjKl0O9KWEqYMRWbzOLGmxjKJcO2Ij56NLa9HCwwuA1CgEdBy5MI9/LeVk0IIZ9Ty4B05nPF5DYw4d+HRxm5UuINb1bmE2EUCcOy1qcira7Q4RHVzt+H1je90PNO72vzuaIBbFsRbR49aPlefBROg9Ptl3sMCSPegnxHhkwoTUorU8QUiWSVpiIg=
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
